const css = document.createElement('style');
const  e = document.querySelector('.close_video')
  e.addEventListener('click', () => { history.go(-1);})
  css.type = 'text/css';
// string styles is a css stylesheet for the widget and iframe
  const styles = " #top_header_nav{top: -38px} #header_nav{top: -3px}body {background: #464545;} .well{background-color: #555; border:0}  .avg-rating>span{ display: none }   .badge-thumb-wrap span.points { display: none }   .progress_bar_curve {display: none; !important}    .group-num{display: none}  .badge-thumb-wrap{margin-bottom: 0;}  .badge-thumb-wrap .well{height: 89% !important;  background-color: rgba(255,255,255,0.15);}   .progress{display: none}   .well-group.wrapText{height: 50% !important;}  .group-img img {}   .bar.bar-warning {display: none;}   .row{margin: -9px 0 0 -17px;}   .badge-img{ width: 183px;height: 167px;margin: -10px auto 0; border: none; border-radius:0;}    .span4.affix{border-right: none; box-shadow: 2px 5px 20px 3px rgba(0, 0, 0, 0.25); background: #555;}   .cl .added.active{border-radius: 0px 40px 40px 3px; background-color: #000000;}   .challenges-scope .added {border-left: 4px solid #bc1f45 !important;}    .nav-pills>.active>a, .nav-pills>.active>a:hover, .nav-pills>.active>a:focus {color: white;}  ul.sidebar-ul li {border-left: 0 solid #FFF;} a:hover, a:focus {color: #bc1f45;}  a {color: #fff;} .navbar .time-score, .navbar .points-score {display: none;}#top_header_nav>.top_hdr_div {color: #382d2d;padding: 57.5px 83px 28.5px 607px;}.badge-thumb-wrap .well:hover {box-shadow: 0 5px 30px 0 rgba(0,0,0,0.2);-webkit-box-shadow: 0 5px 30px 0 rgba(0, 0, 0, 1);-moz-box-shadow: 0 5px 30px 0 rgba(0,0,0,0.2);transform: translateY(-4px);}#challenge_popup .settings_challenge { display: none} div#components { display: none; } .top_hdr_div{    z-index: -3; position: relative; top: 55px; left: 600px; width: 350px; padding: 0 !important} "
  if (css.styleSheet) css.styleSheet.cssText = styles;
  else css.appendChild(document.createTextNode(styles));
  document.head.appendChild(css);
  document.getElementById('store').style.display='none'
//   document.getElementByClassName('points-score user_points overall_points')[0].style.display='none'
